name: Build Unsigned IPA for ESign

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-15
    defaults:
      run:
        working-directory: ./ipa

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ipa/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Expo Prebuild
        run: npx expo prebuild --platform ios --clean

      - name: Install Pods
        run: |
          cd ios
          pod install

      - name: Build Archive (No Signing)
        run: |
          cd ios
          # [SỬA LỖI] Lấy tên scheme từ tên file workspace
          SCHEME=$(basename *.xcworkspace .xcworkspace)
          echo "Detected Scheme: $SCHEME"
          
          xcodebuild archive \
            -workspace *.xcworkspace \
            -scheme "$SCHEME" \
            -configuration Release \
            -archivePath ../build/MyApp.xcarchive \
            -sdk iphoneos \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY=""

      - name: Create IPA from Archive
        run: |
          mkdir -p build/Payload
          mv build/MyApp.xcarchive/Products/Applications/*.app build/Payload/
          cd build
          zip -r -9 MyApp.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: ipa/build/Lich.ipa